<?php if (! empty($this->form)): ?>
	<?php echo $this->form; ?>
<?php endif; ?>

<?php if (! empty($this->linklist)): ?>
<div id="linklist">
	<table>
		<?php foreach ($this->linklist as $link): ?>

		<tr id="item_<?php echo $link->getId(); ?>" class="item">
<!--			<td class="id"><?php echo $link->getId(); ?></td>-->
			<td class="thumb" rowspan="2">
				<img src="/img/static/nothumb.png" class="previewThumb" alt="Vorschau nicht verfügbar!" title="Vorschau nicht verfügbar!" />
			</td>
			<td>
				<a href="<?php echo $link->getReference(); ?>">
					<?php echo $link->getLinktext(); ?>
				</a>
			</td>
		</tr>

		<tr>
			<td>
				<button class="del is_linkctrl_del" value="<?php echo $link->getId(); ?>">del</button>
				<button class="edt is_linkctrl_edt" value="<?php echo $link->getId(); ?>">edit</button>
			</td>
		</tr>

		<?php endforeach; ?>
	</table>
</div>
<?php endif; ?>