<div id="formbox">
<?php if (! empty($this->form)): ?>
	<?php echo $this->form; ?>
<?php endif; ?>
</div>

<?php if (! empty($this->taglist)): ?>
<div id="taglist">
	<ul>
	<?php foreach ($this->taglist as $idx => $tag): ?>
		<li class="is_tag tagWeight<?php echo $tag['cnt']; ?>">
			<?php echo $tag['tagname']; ?>
		</li>
	<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>

<?php if (! empty($this->linklist)): ?>
<div id="linklist">
	<?php foreach ($this->linklist as $link): ?>
	<div id="item_<?php echo $link->getId(); ?>" class="item">
		<div class="previewThumb" title="Vorschau nicht verfügbar!"></div>
		<div class="infocontrol">
			<div>
				<a href="<?php echo $link->getReference(); ?>"><?php echo $link->getLinktext(); ?></a>
			</div>
			<div class="tags">
				<span class="small">Schlagwörter:</span> <?php echo $this->arrayToString($link->getTags()); ?>
			</div>
			<div class="buttons">
				<button class="delete is_linkctrl_del" value="<?php echo $link->getId(); ?>">del</button>
				<button class="save is_linkctrl_edt" value="<?php echo $link->getId(); ?>">edit</button>
			</div>
		</div>
	</div>

	<?php endforeach; ?>
</div>
<?php endif; ?>