<div id="formbox">
<?php if (! empty($this->form)): ?>
	<?php echo $this->form; ?>
<?php endif; ?>
</div>

<?php if (! empty($this->taglist)): ?>
<div id="taglist">
	<ul>
	<?php foreach ($this->taglist as $idx => $tag): ?>
		<li class="is_tag tagWeight<?php echo $tag['cnt']; ?>">
			<?php echo $tag['tagname']; ?>
		</li>
	<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>

<?php if (! empty($this->linklist)): ?>
<div id="linklist">
	<table>
		<?php foreach ($this->linklist as $link): ?>

		<tr id="item_<?php echo $link->getId(); ?>" class="item">
			<td class="thumb" rowspan="3">
				<div class="previewThumb" title="Vorschau nicht verfügbar!"></div>
			</td>
			<td>
				<a href="<?php echo $link->getReference(); ?>">
					<?php echo $link->getLinktext(); ?>
				</a>
			</td>
		</tr>
		<tr>
			<td><?php echo $this->arrayToString($link->getTags()); ?></td>
		</tr>
		<tr>
			<td>
				<button class="del is_linkctrl_del" value="<?php echo $link->getId(); ?>">del</button>
				<button class="edt is_linkctrl_edt" value="<?php echo $link->getId(); ?>">edit</button>
			</td>
		</tr>

		<?php endforeach; ?>
	</table>
</div>
<?php endif; ?>