<?php if ($this->linklist->count() > 0): ?>
	<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml', array('cssType' => 'top')); ?>
	<?php foreach ($this->linklist as $link): ?>
	<div id="item_<?php echo $link->getId(); ?>" class="item">
		<div class="previewThumb" title="Vorschau nicht verfügbar!"></div>
		<div class="infocontrol">
			<div>
				<a href="<?php echo $link->getReference(); ?>"><?php echo $link->getLinktext(); ?></a>
			</div>
			<div class="tags">
				<span class="small">Schlagwörter:</span> <?php // echo $this->arrayToString($link->getTags()); ?>
			</div>
			<div class="buttons">
				<button class="delete is_linkctrl_del" value="<?php echo $link->getId(); ?>">del</button>
				<button class="save is_linkctrl_edt" value="<?php echo $link->getId(); ?>">edit</button>
			</div>
		</div>
	</div>
	<?php endforeach; ?>
	<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml', array('cssType' => 'bottom')); ?>
<?php endif; ?>