<?php echo $this->doctype() . PHP_EOL; ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php echo $this->headMeta() . PHP_EOL; ?>
	<?php echo $this->headTitle() . PHP_EOL; ?>
	<?php
		$this->loadSkin($this->skin);
		echo $this->headLink() . PHP_EOL;

		echo $this->headScript() . PHP_EOL;
	?>
</head>

<body>
	<div id="sitewrapper">
		<div id="header"><h1>Link-Fu</h1></div>
		<div id="content">
			<?php echo $this->layout()->content; ?>
		</div>
		<div id="footer">

		</div>
	</div>
</body>
</html>
